name: GitHell

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Ensure abyss folder exists
        run: mkdir -p abyss

      - name: Track execution
        id: execution_data
        run: |
          if [ -f abyss/README.yml ]; then
            execution_count=$(grep -oP '(?<=Execution Count: )\d+' abyss/README.yml | tail -1)
            execution_count=$((execution_count + 1))
          else
            execution_count=1
          fi
          echo "execution_count=$execution_count" >> $GITHUB_ENV

      - name: Commit and Push Changes
        run: |
          git config user.name "tadanobutubutu"
          git config user.email "58510538+tadanobutubutu@users.noreply.github.com"
          current_time=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

          commit_id=$(cat /proc/sys/kernel/random/uuid)
          total_commits=$(git rev-list --count HEAD)

          echo "  _________.__  __     ___ ___         .__  .__   " > abyss/README.yml
          echo " /  _____/|__|/  |_  /   |   \\   ____ |  | |  |  " >> abyss/README.yml
          echo "/   \\  __ |  \\   __\\/    ~    \\_/ __ \\|  | |  |  " >> abyss/README.yml
          echo "\\    \\_\\  \\|  |  |  \\    Y    /\\  ___/|  |_|  |__" >> abyss/README.yml
          echo " \\______  /|__|__|   \\___|_  /  \\___  >____/____/" >> abyss/README.yml
          echo "        \\/                 \\/       \\/           " >> abyss/README.yml
          echo "--------------------------------------------------" >> abyss/README.yml
          echo "The abyss grows deeper with each commit." >> abyss/README.yml
          echo "--------------------------------------------------" >> abyss/README.yml
          echo "Commit ID: $commit_id" >> abyss/README.yml
          echo "Commit: $total_commits" >> abyss/README.yml
          echo "Execution Count: ${{ env.execution_count }}" >> abyss/README.yml
          echo "Last Execution Time: $current_time" >> abyss/README.yml
          echo "--------------------------------------------------" >> abyss/README.yml

          git add abyss/README.yml
          git commit -m "🚀 The abyss has no bottom... (Total commits: $total_commits, Executions: ${{ env.execution_count }}, Last run: $current_time)"
          
          git push
